// Code generated by goctl. DO NOT EDIT!
// Source: main.proto

package server

import (
	"context"

	"zero/rpc/internal/logic"
	"zero/rpc/internal/svc"
	"zero/rpc/pb"
)

type ServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedServiceServer
}

func NewServiceServer(svcCtx *svc.ServiceContext) *ServiceServer {
	return &ServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *ServiceServer) Ping(ctx context.Context, in *pb.Request) (*pb.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}

func (s *ServiceServer) Greet(ctx context.Context, in *pb.Request) (*pb.Response, error) {
	l := logic.NewGreetLogic(ctx, s.svcCtx)
	return l.Greet(in)
}
