version: "3"

includes:
  chart:
    aliases: [ "c", "ch" ]
    taskfile: try-go-echart/
    dir: try-go-echart/



#
# global vars: https://taskfile.dev/#/usage?id=variables
#
vars:
  VAR1: "some-var"

# global env:
env:
  ENV1: testing

################################################################################################


tasks:
  setup:
    cmds:
      - go install github.com/wailsapp/wails/v2/cmd/wails@latest
      - wails
      - wails doctor

  info:
    aliases: [ "debug", "doctor" ]
    cmds:
      - wails doctor

  run:
    aliases: [ "r" ]
    cmds:
      - wails dev
    dir: ./try-wails-vue-quasar

  new:
    aliases: [ "n" ]
    cmds:
      - wails init -n "try-wails-vue-quasar" -t https://github.com/sgosiaco/wails-template-quasar-ts

  new:vue:
    aliases: [ "nv" ]
    cmds:
      - wails init -n try-wails-vue -t vue-ts

  go:work:
    cmds:
      - go work use ./try-wails-vue
      - go work use ./try-wails-vue-quasar

  run:vue:
    aliases: [ "rv" ]
    cmds:
      - wails dev
    dir: try-wails-vue/

  build:vue:
    aliases: [ "bv" ]
    cmds:
      #      - go work use .
      - wails build
    dir: try-wails-vue/


  wails:
    cmds:
      - wails {{.CLI.ARGS}}
      - wails generate module
    dir: try-wails-vue/
