version: "3"

includes:
  flet:
    aliases: [ "f", "fl" ]
    taskfile: try-flet/
    dir: try-flet/
    optional: true

  pyside:
    aliases: [ "ps", "p" ]
    taskfile: try-pyside/
    dir: try-pyside/
    optional: true

#
# global vars: https://taskfile.dev/#/usage?id=variables
#
vars:
  VAR1: "some-var"

# global env:
env:
  ENV1: testing

################################################################################################


tasks:
  setup:
    cmds:
      - go install github.com/wailsapp/wails/v2/cmd/wails@latest
      - wails
      - wails doctor

  info:
    aliases: [ "debug", "doctor" ]
    cmds:
      - wails doctor


  new:vue:
    aliases: [ "nv" ]
    cmds:
      - wails init -n try-wails-vue -t vue-ts

  go:work:
    cmds:
      - go work use ./try-wails-vue

  run:vue:
    aliases: [ "rv" ]
    cmds:
      - wails dev
    dir: try-wails-vue/

  build:vue:
    aliases: [ "bv" ]
    cmds:
      #      - go work use .
      - wails build
    dir: try-wails-vue/

