// Code generated by goctl. DO NOT EDIT!
// Source: inner.proto

package server

import (
	"context"

	"zero/inner/inner"
	"zero/inner/internal/logic"
	"zero/inner/internal/svc"
)

type InnerServer struct {
	svcCtx *svc.ServiceContext
	inner.UnimplementedInnerServer
}

func NewInnerServer(svcCtx *svc.ServiceContext) *InnerServer {
	return &InnerServer{
		svcCtx: svcCtx,
	}
}

func (s *InnerServer) Ping(ctx context.Context, in *inner.Request) (*inner.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
