version: "3"


#
# global vars: https://taskfile.dev/#/usage?id=variables
#
vars:
  VAR1: "some-var"

# global env:
env:
  ENV1: testing
#  OUT_DIR: "/Users/dev/Documents/iSpace/better-go/matrix/app/try/volo-example"


# env file:
#dotenv:
#  - .env

################################################################################################

tasks:

  run:
    cmds:
      - go run main.go

  init:
    cmds:
      - go mod init fiber

  add:
    cmds:
      - go get -u github.com/gofiber/fiber/v2

  tidy:
    cmds:
      - go mod tidy -v
