version: "3"


#
# global vars: https://taskfile.dev/#/usage?id=variables
#
vars:
  VAR1: "some-var"

# global env:
env:
  ENV1: testing
#  OUT_DIR: "/Users/dev/Documents/iSpace/better-go/matrix/app/try/volo-example"


# env file:
#dotenv:
#  - .env

################################################################################################

tasks:

  run:
    cmds:
      - go run main.go

  # ref: https://go-zero.dev/cn/docs/goctl/installation/
  install:
    cmds:
      - GOPROXY=https://goproxy.cn/,direct go install github.com/zeromicro/go-zero/tools/goctl@latest
      - goctl -v
      - goctl env check -i -f --verbose

  run:api:
    cmds:
      - |
        cd hello; go run hello.go -f etc/hello-api.yaml

  new:api:
    cmds:
      - goctl api new hello

  new:api:docker:
    - cd hello; goctl docker -go hello.go

  new:rpc:
    cmds:
      - goctl rpc new rpc

  build:docker:api:
    cmds:
      - docker build -t hello:v1 -f hello/Dockerfile .

  tidy:
    cmds:
      - go mod tidy -v

  api:test:
    cmds:
      - curl -i -X GET http://localhost:8888/from/you
      - open http://localhost:8888/from/you
