version: "3"

vars:
  VAR1: "some-var"

# global env:
env:
  ENV1: testing



# env file:
#dotenv:
#  - .env

################################################################################################

tasks:

  run:
    aliases: [ "r" ]
    cmds:
      - go run main.go

  r3:
    aliases: [ "run3" ]
    cmds:
      - go run run3/main.go

  r2:
    aliases: [ "run2" ]
    cmds:
#      - EMAIL="your_email" PASSWORD="your_password" go run run2/main.go
      - go run run2/main.go

  r1:
    aliases: [ "run1" ]
    cmds:
      - go run script/main.go

  install:
    aliases: [ "i" ] # install deps
    cmds:
      - echo "install deps"

  get:
    cmds:
      - go get -u github.com/sirupsen/logrus
      - go get -u github.com/adshao/go-binance/v2

  init:
    cmds:
      - go mod init try-binance

  work:
    cmds:
      - go work use .

  tidy:
    cmds:
      - go mod tidy -v
