version: "3"

vars:
  VAR1: "some-var"

# global env:
env:
  ENV1: testing



# env file:
#dotenv:
#  - .env

################################################################################################

tasks:
  run:
    aliases: [ "r" ]
    cmds:
      - go mod tidy -v
      - go run main.go

  install:
    aliases: [ "i" ] # install deps
    cmds:
      - echo "install deps"

  get:
    cmds:
      - go get -u "github.com/k0kubun/pp/v3"
      - go get -u github.com/go-echarts/go-echarts/v2/...

  init:
    cmds:
      - go mod init try-go-echart

  work:
    cmds:
      - go work use .

  tidy:
    cmds:
      - go mod tidy -v
