version: "3"

vars:
  VAR1: "some-var"

# global env:
env:
  ENV1: testing



# env file:
#dotenv:
#  - .env

################################################################################################

tasks:

  run:
    aliases: [ "r" ]
    cmds:
      - go run main.go

  r3:
    aliases: [ "run3" ]
    cmds:
      - go run run3/main.go

  r2:
    aliases: [ "run2" ]
    cmds:
#      - EMAIL="your_email" PASSWORD="your_password" go run run2/main.go
      - go run run2/main.go

  r1:
    aliases: [ "run1" ]
    cmds:
      - go run script/main.go

  i:
    cmds:
      # - go install github.com/goreleaser/goreleaser@latest
      - brew install goreleaser
  init:
    cmds:
      - goreleaser init

  init2:
    cmds:
      - goreleaser init
    dir: run2/

  rel2:
    cmds:
      - goreleaser release --skip=publish --snapshot
    dir: run2/

  rel:
    cmds:
      - goreleaser release --skip=publish --snapshot


  # ref: https://playwright.dev/docs/install
  install:all:
    aliases: [ "ia" ] # install deps
    cmds:
      - go run github.com/playwright-community/playwright-go/cmd/playwright@latest install --with-deps

  get:
    cmds:
      - go get -u github.com/playwright-community/playwright-go
      - go get -u github.com/sirupsen/logrus
      - go get -u github.com/gocolly/colly/v2
      - go get -u github.com/carlmjohnson/requests


  tidy:
    cmds:
      - go mod tidy -v
