// Code generated by goctl. DO NOT EDIT!
// Source: inner.proto

package innerclient

import (
	"context"

	"zero/inner/inner"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = inner.Request
	Response = inner.Response

	Inner interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultInner struct {
		cli zrpc.Client
	}
)

func NewInner(cli zrpc.Client) Inner {
	return &defaultInner{
		cli: cli,
	}
}

func (m *defaultInner) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := inner.NewInnerClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
